# Generated by Django 4.1.3 on 2022-11-10 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('ref', models.UUIDField(verbose_name=uuid.UUID('66d99739-64c2-42f8-99c2-7151ea9f3a52'))),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=225)),
                ('receiver', models.CharField(max_length=225)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_by', models.CharField(max_length=225)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pal.network')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pal.networkresponse')),
            ],
        ),
    ]
